name: Deploy Discord Bot and Web Server

on:
  push:
    branches:
      - main  # or master, depending on your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        pip install pytest
        pytest
    
    - name: Set up environment variables
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        # Add other necessary environment variables here
      run: |
        echo "DISCORD_TOKEN=$DISCORD_TOKEN" >> .env
        # Add other environment variables to .env file
    
    - name: Run Discord bot and Web Server
      run: |
        python bot.py &
        python web_interface.py